{
 "title": "Postgres",
 "tags": [ "postgres" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"leaderboard\"}",
     "legendFormat": "backends"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"leaderboard\"}[1m])",
     "legendFormat": "commits"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"leaderboard\"}[1m])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Tuples returned/fetched/inserted/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"leaderboard\"}[1m])",
     "legendFormat": "returned"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"leaderboard\"}[1m])",
     "legendFormat": "fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"leaderboard\"}[1m])",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"leaderboard\"}[1m])",
     "legendFormat": "updated"
    }
   ]
  }
 ]
}